#!/bin/python3

import math
import os
import random
import re
import sys

#
# Complete the 'gradingStudents' function below.
#
# The function is expected to return an INTEGER_ARRAY.
# The function accepts INTEGER_ARRAY grades as parameter.
#
def calculateOneGrade(grade):
    if grade < 38:
        return grade
    
    next_multiple = 5 * (grade // 5 + 1)
    if next_multiple - grade < 3:
        return next_multiple
    return grade
    

def gradingStudents(grades):
    score = []
    for grade in grades:
        current_grade = calculateOneGrade(grade)
        score.append(current_grade)
        
    return score

# def result(grade) :
    
    
    
    


    

if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    grades_count = int(input().strip())

    grades = []

    for _ in range(grades_count):
        grades_item = int(input().strip())
        grades.append(grades_item)

    result = gradingStudents(grades)

    fptr.write('\n'.join(map(str, result)))
    fptr.write('\n')

    fptr.close()
